### ISSUE TITLE
Unknown error on console

### ISSUE THREAD

**Issue by MetalGearDaner** [Coutume/ImageOnMap#5]
There is an error on console, this is the print:

http://paste.ofcode.org/JdGYR4T4PHQCvhz4VqFDGp

I don't really know when this appears, but It is very frequent.

**Comment by prokopyl** [comment]
It seems to happen when the plugin tries to load a map that was previously incorrectly saved by the plugin (probably because of #3). 
If you are trying the plugin on a development server of yours, I suggest you clean up the plugins data folder, it should fix the problem.

However, the plugin should handle invalid data/configuration files flawlessly, so I'll still mark it as a bug, and I will try to fix it as soon as possible.

**Comment by MetalGearDaner** [comment]
Thank you very muck. I'll wait till the next release :+1:

**Comment by prokopyl** [comment]
Won't fix, as this only affects an old and buggy development version (see #8 for a proper explanation).
